import type { ExtractedRequirement } from "@payna/shared";

// Deterministic mock: when LLM_API_KEY is unset and
// MOCK_EXTRACTION=true, return two plausible records so the full
// parse -> validate -> upsert -> respond path is demo-able offline.
export function mockExtraction(): ExtractedRequirement[] {
  return [
    {
      name: "Mock Annual Compliance Report",
      description: "Annual compliance report generated by the deterministic extraction mock.",
      stateCode: "CA",
      licenseTypeName: "Money Transmitter License",
      intervalMonths: 12,
      dueMonthDay: "04-15",
      formNumber: "MOCK-1",
      agency: "Mock Regulatory Agency",
      dependsOnNames: [],
      confidence: 0.99,
    },
    {
      name: "Mock Fidelity Bond Renewal",
      description: "Fidelity bond renewal generated by the deterministic extraction mock.",
      stateCode: "CA",
      licenseTypeName: "Money Transmitter License",
      intervalMonths: 12,
      dueMonthDay: null,
      dependsOnNames: ["Mock Annual Compliance Report"],
      confidence: 0.95,
    },
  ];
}
